vim.api.nvim_set_keymap('n', '<leader>h', '<C-w>h', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>j', '<C-w>j', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>k', '<C-w>k', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<leader>l', '<C-w>l', {silent = true, noremap = true})
vim.api.nvim_set_keymap('n', '<F2>', ':NvimTreeToggle<CR>', {silent = true})
vim.api.nvim_set_keymap('n', '<A-j>', ':m .+1<CR>==', {noremap = true})
vim.api.nvim_set_keymap('n', '<A-k>', ':m .-2<CR>==', {noremap = true})
vim.api.nvim_set_keymap('i', '<A-j>', '<Esc>:m .+1<CR>==gi', {silent = true, noremap = true})
vim.api.nvim_set_keymap('i', '<A-k>', '<Esc>:m .-2<CR>==gi', {silent = true, noremap = true})
vim.api.nvim_set_keymap('v', '<A-j>', ':m >+1<CR>gv=gv', {silent = true, noremap = true})
vim.api.nvim_set_keymap('v', '<A-k>', ':m <-2<CR>gv=gv', {silent = true, noremap = true})
